### ISSUE TITLE
AgoraUikit is not working 

### ISSUE THREAD

**Issue by alimajid124** [AgoraIO-Extensions/Agora-Flutter-SDK#686]
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.

A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
Compilation error. See log for more details

e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraRtcEnginePlugin.kt: (146, 18): Type mismatch: inferred type is String? but String was expected
e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraSurfaceViewFactory.kt: (15, 1): Class 'AgoraSurfaceViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraSurfaceViewFactory.kt: (20, 3): 'create' overrides nothing
e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (15, 1): Class 'AgoraTextureViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (20, 3): 'create' overrides nothing

i am using agoraUIkit...
check all solution on stackover flow. nothing works. even i downgraded flutter to 2.10.5 ,it still not work
please help me

**Comment by alimajid124** [comment]
@littleGnAl , Sir, i am using agoraUIkit, so i dont need agora_rtc_engine. also tell me what version should i use of flutter.

**Comment by littleGnAl** [comment]
I think downgrade Flutter SDK to 2.10.5 should works fine, please try to run `flutter clean` first.

**Comment by alimajid124** [comment]
@littleGnAl , run project with flutter clean
using only AgoraUIkit:

e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraRtcEnginePlugin.kt: (146, 18): Type mismatch: inferred type is String? but String was expected
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraSurfaceViewFactory.kt: (15, 1): Class 'AgoraSurfaceViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraSurfaceViewFactory.kt: (20, 3): 'create' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (15, 1): Class 'AgoraTextureViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.2\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (20, 3): 'create' overrides nothing


 Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by littleGnAl** [comment]
I think this error was caused by the user using the Flutter SDK 3.0 to build it, downgrade Flutter SDK to 2.10.5 should fix this error.

**Comment by alimajid124** [comment]
I have downgrade it to 2.10.5  still have this error😔
I am using agoraUIkit

**Comment by littleGnAl** [comment]
Maybe you can try invalidate caches on Android Studio
<img width="290" alt="image" src="https://user-images.githubusercontent.com/8847263/169559094-b2acb3ae-329d-4bd8-917b-815eab66a88f.png">

**Comment by alimajid124** [comment]
Please help me...AgoraUIkit is not working in flutter update. I have to
release app within a week . Please tell when update will come.
